sudo: required
services:
  - docker

before_install:
  - docker build -t johnrk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true johnrk/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_env: "elasticbeanstalk-us-east-2-889628227867"
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: "$AWS_SECRET_KEY"